# Workflow to run CodeQL for actions for the open-api-workflows repo itself

name: CodeQL for actions

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 23 * * 6'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  open-api-workflow-code-analysis:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-analysis.yml@48ef9e12c0f009c6c69ccea96b03cfc4a1d98966  # v6.4.0
    with:
      languages: '["actions"]'

