# Workflow to run CodeQL for actions for the open-api-workflows repo itself

name: CodeQL for actions

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 23 * * 6'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  open-api-workflow-code-analysis:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-analysis.yml@d041ff2ab7ef3c17474e97eb12dd16dadcd0e52d  # pre-v7.0.0
