# https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning

name: open-api-workflow code-analysis

on:
  workflow_call:
    inputs:
      languages:
        description: "JSON list of languages CodeQL should analyze"
        required: false
        type: string
        default: '["python","javascript","actions"]'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(inputs.languages) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # All the codeql-action steps are pinned to the git SHA for v4.34.1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@38697555549f1db7851b81482ff19f1fa5c4fedc
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@38697555549f1db7851b81482ff19f1fa5c4fedc

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@38697555549f1db7851b81482ff19f1fa5c4fedc
