name: Generate and Update Docker Hub description

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of the Docker Hub repository
        required: true
        type: string
      config-file:
        description: Path to the JSON configuration file containing project constants
        required: false
        default: ./docker/ci/config.json
        type: string
      output-file:
        description: Path to the output file where the generated description will be written
        required: false
        default: ./docker/ci/README.md
        type: string

    secrets:
      docker-username:
        required: true
      docker-token:
        required: true

permissions: {}

jobs:
  update-docker-readme:
    name: Generate and update Docker Hub description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Generate README
        uses: maykinmedia/open-api-workflows/actions/dockerhub-description@ec61297c42c9e57db276e2731dca48b168679423
        with:
          config-file: ${{ inputs.config-file }}
          output-file: ${{ inputs.output-file }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-token }}
          repository: ${{ inputs.image-name }}
          readme-filepath: ${{ inputs.output-file }}
