on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 'latest'

      schema-path:
        required: true
        type: string
        description: >
          'Directory where the OAS is located (without trailing slash).'
          'This can be a template string when a project has a nested layout.'
      schema-item:
        required: false
        type: string
        description: >
          'The name of the item of the OAS file being processed. Should'
          'be used in conjuction with `schema-path`.'

jobs:
  schema-path:
    runs-on: ubuntu-latest
    outputs:
      path: >
        ${{ steps.nested-layout.outputs.path || steps.flat-layout.outputs.path }}
    steps:
      - name: Output nested layout schema path
        if: inputs.schema-item
        id: nested-layout
        run: |
          echo \
          "path=${{ format('{0}/{1}/openapi.yaml', inputs.schema-path, inputs.schema-item) }}/openapi.yaml" \
          >> "$GITHUB_OUTPUT"
      - name: Output flat layout schema path
        if: ${{ ! inputs.schema-item }}
        id: flat-layout
        run: echo "path=${{ inputs.schema-path }}/openapi.yaml" >> "$GITHUB_OUTPUT"

  generate-postman-collection:
    name: Generate a postman collection
    runs-on: ubuntu-latest
    needs: ['schema-path']
    steps:
        - uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '${{ inputs.node-version }}'
        - name: Install node dependencies
          run: npm install --global openapi-to-postmanv2
        - name: Create tests folder
          run: mkdir --parents ./tests/postman

        - name: Generate Postman collection
          run: |
            openapi2postmanv2 \
            --spec ${{ needs.schema-path.outputs.path }} \
            --output ./tests/postman/collection.json \
            --pretty
