on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 'latest'

      schema-path:
        required: true
        type: string
        description: 'Location of the OAS file'

jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm install --global @openapitools/openapi-generator-cli

      - name: Validate OAS file
        run: |
          openapi-generator-cli validate \
          --input-spec ${{ inputs.schema-path }}

      - name: Generate Java client
        run: |
          openapi-generator-cli generate \
          --input-spec ${{ inputs.schema-path }} \
          --generator-name java \
          --output ./sdks/java \
          --global-property=modelTests=false,apiTests=false,modelDocs=false,apiDocs=false \
          --additional-properties=dateLibrary=java8,java8=true,optionalProjectFile=false,optionalAssemblyInfo=false

      - name: Generate .NET client
        run: |
          openapi-generator-cli generate \
          --input-spec ${{ inputs.schema-path }} \
          --output ./sdks/net \
          --generator-name csharp \
          --global-property=modelTests=false,apiTests=false,modelDocs=false,apiDocs=false \
          --additional-properties=optionalProjectFile=false,optionalAssemblyInfo=false

      - name: Generate Python client
        run: |
          openapi-generator-cli generate \
          --input-spec ${{ inputs.schema-path }} \
          --output ./sdks/python \
          --generator-name python \
          --global-property=modelTests=false,apiTests=false,modelDocs=false,apiDocs=false \
          --additional-properties=optionalProjectFile=false,optionalAssemblyInfo=false+
