on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 'latest'

jobs:
  generate-postman-collection:
    name: Generate a postman collection
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '${{ inputs.node-version }}'
        - name: Install node dependencies
          run: npm install --global openapi-to-postmanv2
        - name: Create tests folder
          run: mkdir --parents ./tests/postman
        - name: Generate Postman collection
          run: ./bin/generate_postman_collection.sh
