name: open-api-workflow oaf-check

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  oaf-up-to-date:
    name: Check for new OAF version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'
      - name: Install dependencies
        run: pip install $(grep "pip-tools==" requirements/dev.txt)
      - name: Run compile dependencies
        run: ./bin/compile_dependencies.sh --upgrade-package open-api-framework
      - name: Check git diff
        run: git diff --exit-code -- requirements/*.txt
      - name: Save OAF Version
        # save the package version for branch names and commit messages
        if: failure()
        id: save-oaf-version
        run: echo "OAF_VERSION=$(grep --perl-regexp --only-matching '(?<=open-api-framework==)[^\n]*' requirements/dev.txt)" >> $GITHUB_ENV
      - name: Create Update PR
        if: ${{ failure() && steps.save-oaf-version.conclusion == 'success' }}
        uses: maykinmedia/open-api-workflows/actions/create-update-pr@v4-a
        with:
          branch-name: update/open-api-framework-${{env.OAF_VERSION}}
          commit-message: ':arrow_up: Update Open-API-Framework to ${{env.OAF_VERSION}}'
          pr-title: Update Open API Framework to ${{env.OAF_VERSION}}
