name: open-api-workflow oaf-check

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  oaf-up-to-date:
    name: Check for new OAF version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'
      - name: Install dependencies
        run: pip install uv
      - name: Run compile dependencies
        run: ./bin/compile_dependencies.sh --upgrade-package open-api-framework
      - name: Check git diff
        run: git diff --exit-code -- requirements/*.txt
