on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

      django-settings-module:
        required: true
        type: string

      schema-command:
        required: true
        type: string
        description: 'The command which will be used to generate the OAS file(s)'
      schema-options:
        required: true
        type: string
        description: 'The options passed to the `schema-command`'

      # Used for projects with the following OAS layout:
      # - src/<project-name>/api/openapi.yaml (Referentielijsten)
      # - src/<project-name>/openapi.yaml (Open-Notificaties)
      schema-path:
        required: true
        type: string
        description: >
          'Directory where the OAS is located (without trailing slash).'
          'This can be a template string when a project has a nested layout.'

      # Used for projects with the following OAS layout:
      # - src/<project-name>/components/<component>/openapi.yaml (Open-Zaak)
      # - src/<project-name>/api/<version>/openapi.yaml (Objecttypes-API)
      schema-item:
        required: false
        type: string
        description: >
          'The name of the item of the OAS file being processed. Should'
          'be used in conjuction with `schema-path`.'

      apt-packages:
        required: false
        type: string

jobs:
  schema-path:
    runs-on: ubuntu-latest
    outputs:
      path: >
        ${{ steps.nested-layout.outputs.path || steps.flat-layout.outputs.path }}
    steps:
      - name: Output nested layout schema path
        if: inputs.schema-item
        id: nested-layout
        run: |
          echo \
          "path=${{ format('{0}/{1}/openapi.yaml', inputs.schema-path, inputs.schema-item) }}/openapi.yaml" \
          >> "$GITHUB_OUTPUT"
      - name: Output flat layout schema path
        if: ${{ ! inputs.schema-item }}
        id: flat-layout
        run: echo "path=${{ inputs.schema-path }}/openapi.yaml" >> "$GITHUB_OUTPUT"

  oas-up-to-date:
    name: Check for unexepected OAS changes
    runs-on: ubuntu-latest
    needs: ['schema-path']
    steps:
      - uses: actions/checkout@v4
      - name: Set up backend environment
        uses: maykinmedia/setup-django-backend@v1.3
        with:
          apt-packages: ${{ inputs.apt-packages }}
          python-version: ${{ inputs.python-version }}
          setup-node: true

      - name: Generate OAS file
        if: ${{ ! inputs.schema-item }}
        run: |
          src/manage.py ${{ inputs.schema-command }} \
          ${{ inputs.schema-options }} \
          --file "${{ github.workspace }}/openapi.yaml" \
          --validate
        env:
          DJANGO_SETTINGS_MODULE: ${{ inputs.django-settings-module }}

      - name: Compare OAS file
        if: ${{ ! inputs.schema-item }}
        run: |
          cmp --silent \
          ${{ github.workspace }}/openapi.yml \
          ${{ needs.schema-path.outputs.path }}
