name: open-api-workflow oas-check
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

      django-settings-module:
        required: true
        type: string

      schema-command:
        type: string
        description: 'The command which will be used to generate the OAS file(s)'
        default: 'bin/generate_schema.sh'

      schema-path:
        type: string
        description: 'Location of the OAS file'
        default: 'src/openapi.yaml'

      schema-options:
        type: string
        description: 'The options passed to the `schema-command`'
        default: ''

      apt-packages:
        required: false
        type: string

jobs:
  oas-up-to-date:
    name: Check for unexpected OAS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up backend environment
        uses: maykinmedia/setup-django-backend@v1.3
        with:
          apt-packages: ${{ inputs.apt-packages }} gettext
          python-version: ${{ inputs.python-version }}
          setup-node: true

      - name: Compile translations
        run: cd src/ && ./manage.py compilemessages
        env:
          DJANGO_SETTINGS_MODULE: ${{ inputs.django-settings-module }}

      - name: Generate OAS file
        run: ${{ inputs.schema-command }} ${{ inputs.schema-options }}
        env:
          DJANGO_SETTINGS_MODULE: ${{ inputs.django-settings-module }}

      - name: Compare OAS files
        run: git diff --exit-code ${{ inputs.schema-path }}
