name: open-api-workflow publish
on:
  workflow_call:
    inputs:
      docker-image-name:
        required: true
        type: string
        description: "Name for the docker image to be build"

      repository-owner:
        required: true
        type: string
        description: |
          'Name of the repository owner. Used when determining wether to publish or not'

    secrets:
      docker-username:
        required: true

      docker-token:
        required: true

jobs:
  publish:
    name: Push Docker image
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      github.repository_owner == inputs.repository-owner &&
      (github.ref_type == 'tag' || github.ref == format('refs/heads/{0}', github.event.repository.default_branch))

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Ensure all tags are available
        run: git fetch --tags --force

      - name: Download built image
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: docker-image
          run-id: ${{ github.run_id }}

      - name: Determine tag/commit hash
        id: vars
        uses: maykinmedia/open-api-workflows/actions/extract-version@f3918649c67da9bc96991ce64cdbb760b9fed28e  # v6.3.3

      - name: Load image
        run: |
          docker image load -i image.tar

      - name: Log into registry
        run: echo "${{ secrets.docker-token }}" | docker login -u ${{ secrets.docker-username }} --password-stdin

      - name: Push the Docker image
        run: docker push ${INPUTS_DOCKER_IMAGE_NAME}:${STEPS_VARS_OUTPUTS_VERSION}
        env:
          INPUTS_DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
          STEPS_VARS_OUTPUTS_VERSION: ${{ steps.vars.outputs.version }}

      - name: Push stable tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${STEPS_VARS_OUTPUTS_VERSION}"

          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then

            LATEST_TAG=$(git tag --list | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' | sort -V | tail -n1)

            if [[ "$TAG_NAME" == "$LATEST_TAG" ]]; then
              docker tag ${INPUTS_DOCKER_IMAGE_NAME}:$TAG_NAME \
                        ${INPUTS_DOCKER_IMAGE_NAME}:stable
              docker push ${INPUTS_DOCKER_IMAGE_NAME}:stable
              echo "Pushed stable tag for $TAG_NAME"
            else
              echo "$TAG_NAME is not the latest version, skipping stable tag"
            fi
          else
            echo "Tag '$TAG_NAME' is not a stable version, not updating stable docker tag"
          fi
        env:
          STEPS_VARS_OUTPUTS_VERSION: ${{ steps.vars.outputs.version }}
          INPUTS_DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
